const avatar = {
  aadhar: "../../public/images/aadhar.jpg",
  airtel: "../../public/images/airtel.png",
  amazon: "../../public/images/amazon.png",
  axis: "../../public/images/axis.png",
  bigbasket: "../../public/images/bigbasket.jpg",
  blinkit: "../../public/images/blinkit.jpg",
  bsnl: "../../public/images/bsnl.png",
  canbnk: "../../public/images/canara.png",
  canara: "../../public/images/canara.png",
  digilocker: "../../public/images/digilocker.webp",
  electionCommision: "../../public/images/electionCommision.jpg",
  epfo: "../../public/images/epfo.jpg",
  flipkart: "../../public/images/flipkart.png",
  gpay: "../../public/images/gpay.jpg",
  hdfc: "../../public/images/hdfc.png",
  hotstar: "../../public/images/hotstar.webp",
  icici: "../../public/images/icici.png",
  incomeTaxDept: "../../public/images/incomeTaxDept.jpg",
  indianGas: "../../public/images/indianGas.png",
  irctc: "../../public/images/irctc.jpg",
  jio: "../../public/images/jio.png",
  joyalukkas: "../../public/images/joyalukkas.png",
  juspay: "../../public/images/juspay.jpg",
  kotak: "../../public/images/kotakMahindra.jpg",
  makemytrip: "../../public/images/makemytrip.png",
  myntra: "../../public/images/myntra.jpg",
  ola: "../../public/images/ola.jpg",
  passportSevaKendra: "../../public/images/passportSevaKendra.jpg",
  paytm: "../../public/images/paytm.jpg",
  phonePe: "../../public/images/phonePe.png",
  pnb: "../../public/images/pnb.png",
  prime: "../../public/images/prime.webp",
  rbi: "../../public/images/rbi.jpg",
  relianceDigital: "../../public/images/relianceDigital.jpg",
  sbi: "../../public/images/sbi.png",
  snapdeal: "../../public/images/snapdeal.png",
  swiggy: "../../public/images/swiggy.png",
  uber: "../../public/images/uber.jpg",
  vi: "../../public/images/vi.png",
  zomato: "../../public/images/zomato.png",

  default: "../../public/images/default.png",
};

export default avatar;