// Sender-name -> logo. Files live in /public/images and are served from the site root,
// so paths must be absolute ("/images/..."), not relative to this module. Filenames are
// case-sensitive on most servers, so they match the actual files exactly.
const avatar = {
  aadhar: "/images/aadhar.jpg",
  airtel: "/images/airtel.png",
  amazon: "/images/amazon.png",
  axisbnk: "/images/axis.png",
  bigbasket: "/images/bigbasket.jpg",
  blinkit: "/images/blinkit.jpg",
  bsnl: "/images/bsnl.png",
  canbnk: "/images/canara.png",
  canara: "/images/canara.png",
  digilocker: "/images/digilocker.webp",
  electionCommision: "/images/electionCommision.jpg",
  epfo: "/images/epfo.jpg",
  flipkart: "/images/flipkart.png",
  gpay: "/images/gpay.jpg",
  googlepay: "/images/gpay.jpg",
  hdfc: "/images/hdfc.png",
  hotstar: "/images/hotstar.webp",
  icici: "/images/icici.png",
  incomeTaxDept: "/images/incomeTaxDept.jpg",
  indianGas: "/images/indianGas.png",
  irctc: "/images/irctc.jpg",
  jio: "/images/jio.png",
  joyalukkas: "/images/Joyalukkas.png",
  juspay: "/images/Juspay.jpg",
  kotak: "/images/kotakMahindra.jpg",
  makemytrip: "/images/makemytrip.png",
  myntra: "/images/myntra.jpg",
  ola: "/images/ola.jpg",
  passportSevaKendra: "/images/passportSevaKendra.jpg",
  paytm: "/images/paytm.jpg",
  phonePe: "/images/phonePe.png",
  pnb: "/images/pnb.png",
  punjabnationalbank: "/images/pnb.png",
  prime: "/images/prime.webp",
  rbi: "/images/rbi.jpg",
  relianceDigital: "/images/relianceDigital.jpg",
  sbi: "/images/sbi.png",
  snapdeal: "/images/snapdeal.png",
  swiggy: "/images/swiggy.png",
  uber: "/images/uber.jpg",
  vi: "/images/vi.png",
  zomato: "/images/zomato.png",

  default: "/images/default.png",
};

export default avatar;
